log_error: added support for an error archiving function, to record all errors | setup: now checks for an existing error archive file, and creates it if it does not exist | close_webdriver: added close_webdriver. function attempts to close the webdriver; catches the thrown exception if it fails. | misc: replaced all "driver.close()" statements with "close_webdriver()" statements.